version: '3.4'
services:

  build:
    build:
      context: ./
      dockerfile: docker/Dockerfile
      target: build
      args:
        PHP_BUILD_VERSION: $PHP_BUILD_VERSION
        BUILD_ROOT_PATH: $BUILD_ROOT_PATH
        PHP_TEST_VERSION: $PHP_TEST_VERSION
        NODE_VERSION: $NODE_VERSION
    container_name: "${PROJECT_NAME}_build"
    working_dir: ${BUILD_ROOT_PATH}
    volumes:
      -  ${BASE_PATH}:${BUILD_ROOT_PATH}

  test:
    extra_hosts:
      - "host.docker.internal:${HOST_IP_ADDRESS}"
    build:
      context: ./
      dockerfile: docker/Dockerfile
      target: test
      args:
        BUILD_ROOT_PATH: $BUILD_ROOT_PATH
        PHP_BUILD_VERSION: $PHP_BUILD_VERSION
        PHP_TEST_VERSION: $PHP_TEST_VERSION
        NODE_VERSION: $NODE_VERSION
    container_name: "${PROJECT_NAME}_test"
    working_dir: ${BUILD_ROOT_PATH}
    volumes:
      -  ${BASE_PATH}:${BUILD_ROOT_PATH}
    networks:
      - clearvue

  frontend:
    image: node:${NODE_VERSION}
    container_name: "${PROJECT_NAME}_frontend"
    working_dir: ${BUILD_ROOT_PATH}
    depends_on:
      - backend
    volumes:
      - '${BASE_PATH}:${BUILD_ROOT_PATH}'
    ports:
      - '${HMR_SERVER_PORT}:${HMR_SERVER_PORT}'
      - '${FRONTEND_SERVER_PORT}:${FRONTEND_SERVER_PORT}'
    command: ['yarn', 'dev']

  backend:
    image: nginx:latest
    container_name: "${PROJECT_NAME}_backend"
    working_dir: ${WEBROOT_PATH}
    depends_on:
      - test
    volumes:
      - ${BASE_PATH}:${WEBROOT_PATH}
      - '${BASE_PATH}docker/nginx/templates:/etc/nginx/templates'
      - '/dev/null:/etc/nginx/conf.d/default.conf'
    env_file:
      - .env
    networks:
      - clearvue
    ports:
      - ${BACKEND_SERVER_PORT}:${NGINX_PORT}

networks:
  clearvue:
    driver: bridge
