openapi: 3.0.0
info:
  title: ClearVUE Test
  description: An API spec for a test project.
  version: 0.1.0
servers:
  - url: /api
    description: Dev Server
paths:
  /cities:
    get:
      summary: Returns a list of cities.
      description: Cities, in which events may take place
      operationId: clearvue/test1/api/handlers/city/list
      responses:
        '200':
          description: A list of City objects.
          content:
            application/json: {}
