openapi: 3.0.0

info:
  title: ClearVUE Test
  description: An API spec for a test project.
  version: 0.1.0

servers:
  - url: /api
    description: Dev Server

paths:
  /cities:
    get:
      summary: Returns a list of cities.
      description: Cities, in which events may take place
      operationId: clearvue/test1/api/handlers/city/list
      responses:
        '200':
          description: A list of City objects.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CityList'

components:
  schemas:
    EntityList:
      type: object
      description: A list of entities.
      properties:
        data:
          type: array
          description: The main list data.
          items:
            type: object
            description: A list of resources.
            properties:
              data:
                type: object
                description: A single entity.
              meta:
                type: object
                description: Info about the entity.
                properties:
                  type:
                    type: string
                    description: The entity type.
        meta:
          type: object
          description: Info about the list.
          required:
            - totalRecords
          properties:
            totalRecords:
              type: integer
              description: The total number of records before limit.

    CityList:
      allOf:
        - $ref: '#/components/schemas/EntityList'
        - type: object
          properties:
            data:
              type: array
              items:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/City'

    City:
      type: object
      description: A City.
      required:
        - id
        - label
      properties:
        id:
          type: integer
          description: The City ID.
        label:
          type: string
          description: The City label.


